#!/usr/bin/env bash
# Install nginx web server

sudo apt -y update
sudo apt -y install nginx
sh -c 'echo "Hello World!" | tee /var/www/html/index.html'
sh -c 'echo "server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html;
    }
}" >> /etc/nginx/sites-available/default'
sudo service nginx restart
