#!/usr/bin/env bash 
# Redirection

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null
then
    sudo apt update
    sudo apt install -y nginx
fi

# Create a configuration file for the redirection
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/redirect_config
server {
    listen 80;
    listen [::]:80;

    server_name 54.82.179.102;

    location /redirect_me {
        return 301 https://google.com/new_page;
    }

    # Additional server configurations can be added here if needed

    # Disallow access to hidden files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
EOF'

# Enable the configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/redirect_config /etc/nginx/sites-enabled/

# Check Nginx configuration and restart
sudo nginx -t
sudo systemctl restart nginx

