#!/usr/bin/env bash 
# Redirection

sudo apt-get update
sudo apt-get -y install nginx

sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

# Create a configuration file for the redirection
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        if (\$request_uri ~* "redirect_me") {
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
    }
}
EOF

# Check Nginx configuration and restart
sudo nginx -t && sudo systemctl restart nginx

