#!/usr/bin/env bash
# 404 not found page

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null
then
    sudo apt update
    sudo apt install -y nginx
fi

# Create a custom 404 error page
sudo bash -c 'echo "Ceci n'"'"'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null'

# Configure Nginx to use the custom 404 page
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/custom_404_config
server {
    listen 80;
    listen [::]:80;

    server_name 54.82.179.102;

    root /var/www/html;
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }

    # Additional server configurations can be added here if needed

    # Disallow access to hidden files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
EOF'

# Enable the configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/custom_404_config /etc/nginx/sites-enabled/

# Check Nginx configuration and restart
sudo nginx -t
sudo systemctl restart nginx

