#!/usr/bin/env bash
# 404 not found page setup for Nginx server

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get -y install nginx

# Create a custom 404 error page
sudo sh -c 'echo "Ceci n'"'"'est pas une page." > /var/www/html/404.html'

# Configure Nginx to use the custom 404 page
sudo tee /etc/nginx/sites-available/custom_404_config > /dev/null <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /var/www/html;

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
    }

    # Additional server configurations can be added here if needed

    # Disallow access to hidden files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
EOF

# Enable the configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/custom_404_config /etc/nginx/sites-enabled/

# Check Nginx configuration and restart
sudo nginx -t && sudo systemctl restart nginx

