#!/usr/bin/env bash
# To onfigure Nginx so that its HTTP response will contains a custom header (on web-01 and web-02

sudo apt-get update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx start

