#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend alnox.tech.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 419818-web-01 100.25.192.224:80
        server 419818-web-02 54.209.131.56:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
