#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Requirements:
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
# Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sed -i "$ a frontend web_frontend\n\tbind *:80\n\tmode http\n\tdefault_backend web_backends\n" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a backend web_backends\n\tbalance roundrobin\n\toption forwardfor\n\tserver web-01 89.207.132.170:80 check\n\tserver web-02 89.207.132.170:80 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy restart

