#!/usr/bin/env bash
# Script that displays a list of currently running processes
# This script displays list of currently running processes
# Must show all processes, for all users, including those which might not have a TTY
# Display a user-oriented format
# Show process hierarchy

echo "USER       PID  PPID  PGID   TTY     COMMAND"

ps auxf | awk '{print $1, $2, $3, $4, $7, $11}' | sed 's/ \S*$//'
