#!/usr/bin/env bash
# Script that displays the content of file /etc/passwd

while IFS=":" read -r username _ userid _ _ homedir _
do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $homedir"
done < /etc/passwd
