#!/usr/bin/env bash
# Script that displays content of file /etc/passwd

while IFS=":" read -r username password userid groupid user_info homedir shell
do
    echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $user_info"
    echo
done < /etc/passwd
