#!/usr/bin/env bash
# Script that displays the times for 12 hrs and 59 min

hour=0
minute=1
lines=0

while [ $hour -le 12 ]
do
    while [ $minute -le 59 ]
    do
        printf "%02d:%02d\n" $hour $minute
        minute=$((minute+1))
        lines=$((lines+1))

        if [ $lines -ge 70 ]
        then
            exit
        fi
    done

    minute=0
    hour=$((hour+1))
done
